### ISSUE TITLE
Translation Component

### ISSUE THREAD

**Issue by lannelin** [alan-turing-institute/ARC-SPICE#12]
Translating multiple languages into English.

using model that includes dropout
https://huggingface.co/ybanas/autotrain-fr-en-translate-51410121895

error: [COMET](https://github.com/Unbabel/COMET?tab=readme-ov-file#interpreting-scores) for document level translation error.

UQ: Using [semantic density](https://arxiv.org/pdf/2405.13845) utilising [MC Dropout](https://arxiv.org/abs/1506.02142).

**Comment by J-Dymond** [comment]
Added recent pull request to this issue, so this is implemented now. Could be re-opened when investigating additional models/uncertainty metrics.
