### ISSUE TITLE
Topic Classification Component

### ISSUE THREAD

**Issue by lannelin** [alan-turing-institute/ARC-SPICE#13]
Topic classification

Multi-label classification task with MultiEURLEX

Error measure: Hamming Accuracy/Zero-one accuracy
Uncertainty Quantification: Aggregate over k binary classifiers, entropy of predicted distribution is used for predictive uncertainty (https://proceedings.mlr.press/v70/li17a.html, https://arxiv.org/pdf/2006.11584). Other metrics such as mutual information and variance can be used for the model uncertainty (https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9761166).

**Comment by J-Dymond** [comment]
Added recent pull request to this issue, so this is implemented now. Could be re-opened when investigating additional models/uncertainty metrics.

**Comment by J-Dymond** [comment]
Added recent pull request to this issue, so this is implemented now. Could be re-opened when investigating additional models/uncertainty metrics.
