### ISSUE TITLE
OCR Component

### ISSUE THREAD

**Issue by lannelin** [alan-turing-institute/ARC-SPICE#14]
OCR model to convert images to text. 

Will rely on synthetic data constructed on MultiEURLEX text.

Model: TODO
Error: TODO
UQ: TODO

**Comment by eddableheath** [comment]
Model: Done, using `microsoft/trocr-base-printed`
Error: In progress, using the character error.
UQ: Will be using levenshtein (edit) distance to define metric space from which to derive the distributions from which the UQ will be computed.

**Comment by eddableheath** [comment]
Error is now done.

Unfortunately there is now a new potential problem in that the inference is incredibly slow.
